import { z } from "zod";

/**
 * Mirrors the ERD's `LEASE_CONTRACT` (PRO-15 / SRS 3.5). Form → HTML → PDF,
 * generated by the backend and persisted with a `pdfUrl`.
 *
 * The row intentionally snapshots names / national IDs / rent / address at
 * generation time — do not re-derive them from live USER/PROPERTY later
 * (feature-relationships.md). National IDs appear in the generated PDF only;
 * they stay masked everywhere else in the UI.
 */

export const CreateLeaseContractSchema = z.object({
  ownerName: z.string().min(2),
  ownerNationalId: z.string().regex(/^\d{14}$/, "الرقم القومي 14 رقمًا"),
  tenantName: z.string().min(2),
  tenantNationalId: z.string().regex(/^\d{14}$/, "الرقم القومي 14 رقمًا"),
  rentAmount: z.number().positive(),
  propertyAddress: z.string().min(5),
  startDate: z.string().min(1),
  endDate: z.string().min(1),
  customClauses: z.string().optional(),
});
export type CreateLeaseContract = z.infer<typeof CreateLeaseContractSchema>;

export const LeaseContractSchema = z.object({
  id: z.string(),
  ownerName: z.string(),
  tenantName: z.string(),
  rentAmount: z.number(),
  propertyAddress: z.string(),
  startDate: z.string(),
  endDate: z.string(),
  customClauses: z.string().nullable(),
  pdfUrl: z.string(),
  createdAt: z.string(),
});
export type LeaseContract = z.infer<typeof LeaseContractSchema>;

/**
 * Values the backend can pre-fill from the user's APPROVED eKYC, surfaced only
 * with explicit consent (ASSUMPTIONS.md #18).
 */
export const ContractPrefillSchema = z.object({
  fullName: z.string().nullable(),
  nationalId: z.string().nullable(),
});
export type ContractPrefill = z.infer<typeof ContractPrefillSchema>;
